"""Provider catalog — metadata for every Gravity-supported provider.

Each entry describes the auth kind(s), capabilities, default base URL, and
known models. Used by account.py (schema builder) and main.py (model listing).
"""

from typing import TypedDict, List

class ProviderMeta(TypedDict):
    display_name: str
    auth_kinds: List[str]       # "api_key" | "session_cookie" | "oauth" | "anonymous"
    tool_support: str           # "native" | "json_emulated" | "none"
    structured_output: str      # "native" | "json_instruction" | "none"
    remote_session_mode: str    # "none" | "required" | "optional"
    supports_system_prompt: bool
    default_base_url: str
    models: List[str]
    requires_custom_account: bool
    category: str               # "web" | "api" | "local"
    description: str

PROVIDERS: dict[str, ProviderMeta] = {
    # ── Reverse-engineered web providers ──────────────────────────────────────
    "cursor": {
        "display_name": "Cursor IDE",
        "auth_kinds": ["api_key"],
        "tool_support": "native",
        "structured_output": "json_instruction",
        "remote_session_mode": "none",
        "supports_system_prompt": True,
        "default_base_url": "",
        "models": ["auto", "claude-sonnet-4-5", "claude-sonnet-4-6", "claude-opus-4-6",
                   "gpt-4o", "gpt-4o-mini", "gemini-2.5-pro", "gemini-2.5-flash"],
        "requires_custom_account": True,
        "category": "web",
        "description": "Cursor IDE inference via Connect-RPC protobuf. Supply your refresh token.",
    },
    "windsurf": {
        "display_name": "Windsurf (Codeium)",
        "auth_kinds": ["api_key"],
        "tool_support": "native",
        "structured_output": "json_instruction",
        "remote_session_mode": "none",
        "supports_system_prompt": True,
        "default_base_url": "",
        "models": ["swe-1-6-fast", "swe-1-6", "kimi-k2-6", "devstral"],
        "requires_custom_account": True,
        "category": "web",
        "description": "Codeium Windsurf via Connect-RPC over Go TLS. Supply your token or OTT.",
    },
    "chatgpt": {
        "display_name": "ChatGPT Web",
        "auth_kinds": ["session_cookie", "anonymous"],
        "tool_support": "native",
        "structured_output": "json_instruction",
        "remote_session_mode": "none",
        "supports_system_prompt": True,
        "default_base_url": "",
        "models": ["gpt-4o", "gpt-4o-mini", "o3", "o4-mini", "auto"],
        "requires_custom_account": True,
        "category": "web",
        "description": "ChatGPT web UI via sentinel + PoW flow. Requires a valid session token.",
    },
    "claude": {
        "display_name": "Claude Web (claude.ai)",
        "auth_kinds": ["session_cookie"],
        "tool_support": "native",
        "structured_output": "json_instruction",
        "remote_session_mode": "required",
        "supports_system_prompt": True,
        "default_base_url": "",
        "models": ["claude-opus-4-8", "claude-sonnet-4-6", "claude-haiku-4-5"],
        "requires_custom_account": True,
        "category": "web",
        "description": "claude.ai web. Requires sessionKey cookie (sk-ant-sid…).",
    },
    "gemini": {
        "display_name": "Gemini Web (gemini.google.com)",
        "auth_kinds": ["session_cookie", "anonymous"],
        "tool_support": "json_emulated",
        "structured_output": "json_instruction",
        "remote_session_mode": "none",
        "supports_system_prompt": True,
        "default_base_url": "",
        "models": ["gemini-2.0-flash", "gemini-2.5-flash", "gemini-2.5-pro"],
        "requires_custom_account": False,
        "category": "web",
        "description": "gemini.google.com batchexecute API. Works anonymously or with session cookies.",
    },
    "kiro": {
        "display_name": "AWS Kiro / Q Developer",
        "auth_kinds": ["api_key"],
        "tool_support": "native",
        "structured_output": "json_instruction",
        "remote_session_mode": "none",
        "supports_system_prompt": True,
        "default_base_url": "",
        "models": ["auto", "claude-sonnet-4-5", "claude-sonnet-4-6",
                   "claude-opus-4-6", "gpt-oss-120b"],
        "requires_custom_account": True,
        "category": "web",
        "description": "AWS Kiro via API Gateway. Supply an AWS Q Developer bearer token.",
    },
    "glm": {
        "display_name": "GLM (chat.z.ai)",
        "auth_kinds": ["api_key", "anonymous"],
        "tool_support": "native",
        "structured_output": "json_instruction",
        "remote_session_mode": "none",
        "supports_system_prompt": True,
        "default_base_url": "",
        "models": ["glm-4-flash", "glm-4-plus", "glm-4-air", "glm-z1-air", "glm-z1-flash"],
        "requires_custom_account": False,
        "category": "web",
        "description": "Zhipu GLM / chat.z.ai with HMAC-signed requests. Works guest mode.",
    },
    "antigravity": {
        "display_name": "Antigravity (Google Code Assist Sandbox)",
        "auth_kinds": ["oauth"],
        "tool_support": "native",
        "structured_output": "json_instruction",
        "remote_session_mode": "none",
        "supports_system_prompt": True,
        "default_base_url": "",
        "models": ["gemini-2.5-pro", "gemini-2.5-flash"],
        "requires_custom_account": True,
        "category": "web",
        "description": "Google Code Assist sandbox via FIPS/boring TLS. Requires OAuth tokens.",
    },
    "codex": {
        "display_name": "OpenAI Codex (ChatGPT backend)",
        "auth_kinds": ["api_key"],
        "tool_support": "native",
        "structured_output": "json_instruction",
        "remote_session_mode": "none",
        "supports_system_prompt": True,
        "default_base_url": "",
        "models": ["codex-mini-latest", "o4-mini"],
        "requires_custom_account": True,
        "category": "web",
        "description": "OpenAI Codex via Responses API on ChatGPT backend. Requires OAuth access token.",
    },
    "gemini_cli": {
        "display_name": "Gemini CLI (Google Code Assist API)",
        "auth_kinds": ["oauth"],
        "tool_support": "native",
        "structured_output": "json_instruction",
        "remote_session_mode": "none",
        "supports_system_prompt": True,
        "default_base_url": "",
        "models": ["gemini-2.5-pro", "gemini-2.5-flash", "gemini-2.0-flash"],
        "requires_custom_account": True,
        "category": "web",
        "description": "Google Cloud Code Assist generateContent API. Requires OAuth + project ID.",
    },
    "perplexity": {
        "display_name": "Perplexity Web",
        "auth_kinds": ["session_cookie", "anonymous"],
        "tool_support": "json_emulated",
        "structured_output": "json_instruction",
        "remote_session_mode": "none",
        "supports_system_prompt": False,
        "default_base_url": "",
        "models": ["default", "sonar", "sonar-pro", "sonar-reasoning", "sonar-deep-research"],
        "requires_custom_account": False,
        "category": "web",
        "description": "Perplexity web SSE search endpoint. Works anonymously.",
    },

    # ── Anthropic native API ──────────────────────────────────────────────────
    "anthropic_api": {
        "display_name": "Anthropic API",
        "auth_kinds": ["api_key"],
        "tool_support": "native",
        "structured_output": "json_instruction",
        "remote_session_mode": "none",
        "supports_system_prompt": True,
        "default_base_url": "https://api.anthropic.com/v1",
        "models": ["claude-opus-4-8", "claude-sonnet-4-6", "claude-haiku-4-5-20251001"],
        "requires_custom_account": True,
        "category": "api",
        "description": "Anthropic Messages API (sk-ant-api03-…).",
    },

    # ── OpenAI-compatible API providers ──────────────────────────────────────
    "openai_api": {
        "display_name": "OpenAI API",
        "auth_kinds": ["api_key"],
        "tool_support": "native",
        "structured_output": "json_instruction",
        "remote_session_mode": "none",
        "supports_system_prompt": True,
        "default_base_url": "https://api.openai.com/v1",
        "models": ["gpt-4o", "gpt-4o-mini", "gpt-4.1", "o3", "o4-mini"],
        "requires_custom_account": True,
        "category": "api",
        "description": "OpenAI Chat Completions (sk-…).",
    },
    "groq": {
        "display_name": "Groq",
        "auth_kinds": ["api_key"],
        "tool_support": "native",
        "structured_output": "json_instruction",
        "remote_session_mode": "none",
        "supports_system_prompt": True,
        "default_base_url": "https://api.groq.com/openai/v1",
        "models": ["llama-3.3-70b-versatile", "llama-3.1-8b-instant", "openai/gpt-oss-120b"],
        "requires_custom_account": True,
        "category": "api",
        "description": "Groq fast inference API (gsk_…).",
    },
    "mistral": {
        "display_name": "Mistral AI",
        "auth_kinds": ["api_key"],
        "tool_support": "native",
        "structured_output": "json_instruction",
        "remote_session_mode": "none",
        "supports_system_prompt": True,
        "default_base_url": "https://api.mistral.ai/v1",
        "models": ["mistral-large-latest", "mistral-small-latest", "codestral-latest"],
        "requires_custom_account": True,
        "category": "api",
        "description": "Mistral AI API.",
    },
    "deepseek": {
        "display_name": "DeepSeek",
        "auth_kinds": ["api_key"],
        "tool_support": "native",
        "structured_output": "json_instruction",
        "remote_session_mode": "none",
        "supports_system_prompt": True,
        "default_base_url": "https://api.deepseek.com/v1",
        "models": ["deepseek-chat", "deepseek-reasoner"],
        "requires_custom_account": True,
        "category": "api",
        "description": "DeepSeek API.",
    },
    "xai": {
        "display_name": "xAI Grok",
        "auth_kinds": ["api_key"],
        "tool_support": "native",
        "structured_output": "json_instruction",
        "remote_session_mode": "none",
        "supports_system_prompt": True,
        "default_base_url": "https://api.x.ai/v1",
        "models": ["grok-4", "grok-3", "grok-3-mini"],
        "requires_custom_account": True,
        "category": "api",
        "description": "xAI Grok API.",
    },
    "together": {
        "display_name": "Together AI",
        "auth_kinds": ["api_key"],
        "tool_support": "native",
        "structured_output": "json_instruction",
        "remote_session_mode": "none",
        "supports_system_prompt": True,
        "default_base_url": "https://api.together.xyz/v1",
        "models": ["meta-llama/Llama-3.3-70B-Instruct-Turbo",
                   "Qwen/Qwen2.5-72B-Instruct-Turbo", "deepseek-ai/DeepSeek-V3"],
        "requires_custom_account": True,
        "category": "api",
        "description": "Together AI open-model inference.",
    },
    "cohere": {
        "display_name": "Cohere",
        "auth_kinds": ["api_key"],
        "tool_support": "native",
        "structured_output": "json_instruction",
        "remote_session_mode": "none",
        "supports_system_prompt": True,
        "default_base_url": "https://api.cohere.ai/compatibility/v1",
        "models": ["command-r-plus", "command-r", "command-a-03-2025"],
        "requires_custom_account": True,
        "category": "api",
        "description": "Cohere Command API.",
    },
    "openrouter": {
        "display_name": "OpenRouter",
        "auth_kinds": ["api_key"],
        "tool_support": "native",
        "structured_output": "json_instruction",
        "remote_session_mode": "none",
        "supports_system_prompt": True,
        "default_base_url": "https://openrouter.ai/api/v1",
        "models": ["openai/gpt-4o", "anthropic/claude-sonnet-4",
                   "google/gemini-2.5-pro", "meta-llama/llama-3.3-70b-instruct"],
        "requires_custom_account": True,
        "category": "api",
        "description": "OpenRouter multi-model gateway (sk-or-…).",
    },
    "fireworks": {
        "display_name": "Fireworks AI",
        "auth_kinds": ["api_key"],
        "tool_support": "native",
        "structured_output": "json_instruction",
        "remote_session_mode": "none",
        "supports_system_prompt": True,
        "default_base_url": "https://api.fireworks.ai/inference/v1",
        "models": ["accounts/fireworks/models/llama-v3p3-70b-instruct",
                   "accounts/fireworks/models/deepseek-v3"],
        "requires_custom_account": True,
        "category": "api",
        "description": "Fireworks AI fast inference.",
    },
    "cerebras": {
        "display_name": "Cerebras",
        "auth_kinds": ["api_key"],
        "tool_support": "native",
        "structured_output": "json_instruction",
        "remote_session_mode": "none",
        "supports_system_prompt": True,
        "default_base_url": "https://api.cerebras.ai/v1",
        "models": ["llama-3.3-70b", "llama3.1-8b", "qwen-3-235b-a22b-instruct-2507"],
        "requires_custom_account": True,
        "category": "api",
        "description": "Cerebras fast inference.",
    },
    "sambanova": {
        "display_name": "SambaNova",
        "auth_kinds": ["api_key"],
        "tool_support": "native",
        "structured_output": "json_instruction",
        "remote_session_mode": "none",
        "supports_system_prompt": True,
        "default_base_url": "https://api.sambanova.ai/v1",
        "models": ["Meta-Llama-3.3-70B-Instruct", "DeepSeek-R1"],
        "requires_custom_account": True,
        "category": "api",
        "description": "SambaNova cloud inference.",
    },
    "hyperbolic": {
        "display_name": "Hyperbolic Labs",
        "auth_kinds": ["api_key"],
        "tool_support": "native",
        "structured_output": "json_instruction",
        "remote_session_mode": "none",
        "supports_system_prompt": True,
        "default_base_url": "https://api.hyperbolic.xyz/v1",
        "models": ["meta-llama/Llama-3.3-70B-Instruct", "deepseek-ai/DeepSeek-V3"],
        "requires_custom_account": True,
        "category": "api",
        "description": "Hyperbolic Labs inference.",
    },
    "nvidia_nim": {
        "display_name": "NVIDIA NIM",
        "auth_kinds": ["api_key"],
        "tool_support": "native",
        "structured_output": "json_instruction",
        "remote_session_mode": "none",
        "supports_system_prompt": True,
        "default_base_url": "https://integrate.api.nvidia.com/v1",
        "models": ["meta/llama-3.3-70b-instruct", "deepseek-ai/deepseek-r1"],
        "requires_custom_account": True,
        "category": "api",
        "description": "NVIDIA NIM microservices.",
    },
    "qwen": {
        "display_name": "Alibaba Qwen",
        "auth_kinds": ["api_key"],
        "tool_support": "native",
        "structured_output": "json_instruction",
        "remote_session_mode": "none",
        "supports_system_prompt": True,
        "default_base_url": "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
        "models": ["qwen-max", "qwen-plus", "qwen2.5-72b-instruct"],
        "requires_custom_account": True,
        "category": "api",
        "description": "Alibaba Cloud DashScope Qwen API.",
    },
    "minimax": {
        "display_name": "MiniMax",
        "auth_kinds": ["api_key"],
        "tool_support": "native",
        "structured_output": "json_instruction",
        "remote_session_mode": "none",
        "supports_system_prompt": True,
        "default_base_url": "https://api.minimax.io/v1",
        "models": ["MiniMax-M2", "abab6.5s-chat"],
        "requires_custom_account": True,
        "category": "api",
        "description": "MiniMax API.",
    },
    "vertex": {
        "display_name": "Google Vertex AI",
        "auth_kinds": ["api_key"],
        "tool_support": "native",
        "structured_output": "json_instruction",
        "remote_session_mode": "none",
        "supports_system_prompt": True,
        "default_base_url": "https://aiplatform.googleapis.com/v1",
        "models": ["google/gemini-2.5-pro", "google/gemini-2.5-flash"],
        "requires_custom_account": True,
        "category": "api",
        "description": "Google Vertex AI Gemini endpoint. Supply per-project base_url.",
    },
    "huggingface": {
        "display_name": "HuggingFace Inference",
        "auth_kinds": ["api_key"],
        "tool_support": "json_emulated",
        "structured_output": "json_instruction",
        "remote_session_mode": "none",
        "supports_system_prompt": True,
        "default_base_url": "https://router.huggingface.co/v1",
        "models": ["meta-llama/Llama-3.3-70B-Instruct"],
        "requires_custom_account": True,
        "category": "api",
        "description": "HuggingFace Inference Router.",
    },
    "litellm": {
        "display_name": "LiteLLM Proxy",
        "auth_kinds": ["api_key", "anonymous"],
        "tool_support": "native",
        "structured_output": "json_instruction",
        "remote_session_mode": "none",
        "supports_system_prompt": True,
        "default_base_url": "http://localhost:4000/v1",
        "models": [],
        "requires_custom_account": False,
        "category": "local",
        "description": "Self-hosted LiteLLM proxy. Point base_url at your server.",
    },

    # ── Local servers ─────────────────────────────────────────────────────────
    "ollama": {
        "display_name": "Ollama (local)",
        "auth_kinds": ["anonymous"],
        "tool_support": "native",
        "structured_output": "json_instruction",
        "remote_session_mode": "none",
        "supports_system_prompt": True,
        "default_base_url": "http://localhost:11434/v1",
        "models": ["llama3.3", "qwen2.5", "phi4", "gemma3", "mistral"],
        "requires_custom_account": False,
        "category": "local",
        "description": "Local Ollama server.",
    },
    "llama_cpp": {
        "display_name": "llama.cpp (local)",
        "auth_kinds": ["anonymous"],
        "tool_support": "json_emulated",
        "structured_output": "json_instruction",
        "remote_session_mode": "none",
        "supports_system_prompt": True,
        "default_base_url": "http://localhost:8080/v1",
        "models": [],
        "requires_custom_account": False,
        "category": "local",
        "description": "Local llama.cpp server.",
    },
    "local_transformers": {
        "display_name": "HuggingFace Transformers (local)",
        "auth_kinds": ["anonymous"],
        "tool_support": "json_emulated",
        "structured_output": "json_instruction",
        "remote_session_mode": "none",
        "supports_system_prompt": True,
        "default_base_url": "http://localhost:8000/v1",
        "models": [],
        "requires_custom_account": False,
        "category": "local",
        "description": "Local HuggingFace transformers server.",
    },
}

# Providers that work without any custom account in the default shared pool.
FREE_PROVIDERS = {k for k, v in PROVIDERS.items() if not v["requires_custom_account"]}

# All known model→provider mappings for smart resolution.
MODEL_TO_PROVIDER: dict[str, str] = {}
for _pname, _pmeta in PROVIDERS.items():
    for _model in _pmeta["models"]:
        if _model not in MODEL_TO_PROVIDER:
            MODEL_TO_PROVIDER[_model] = _pname
